[project]
name = "modernrpc-demo"
version = "1.0.0"
description = "Demo website for django-modern-rpc"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=4.2.22",
    "django-analytical>=3.1.0",
    "django-environ>=0.11.0",
    "django-modern-rpc>=1.1.0",
    "psycopg>=3.2.0",
    "whitenoise>=6.2.0",
]

[dependency-groups]
prod = [
    "gunicorn>=23.0.0",
]
