[tool.poetry]
name = "modernrpc-demo"
version = "1.0.0"
description = ""
authors = ["Antoine Lorence <alorence@flokod.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

django = "^4.2.21"
django-analytical = "^3.1.0"
django-environ = "^0.11.0"
psycopg = "^3.2.0"
whitenoise = "^6.2.0"

django-modern-rpc = "^1.1.0"
# Use this instead while developing
#django-modern-rpc = { path = "../django-modern-rpc/", develop = true }


[tool.poetry.group.prod]
optional = true

[tool.poetry.group.prod.dependencies]
gunicorn = "^23.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
