# Exported from Render on 2024-12-20T08:56:29Z
version: "1"

services:
- type: web
  name: modernrpc
  runtime: python
  repo: https://github.com/alorence/modernrpc_demo
  plan: free

  region: frankfurt
  buildCommand: uv sync --group prod
  startCommand: uv run python manage.py collectstatic && uv run python manage.py migrate && gunicorn modernrpc_demo.wsgi:application --log-file -

  envVars:
  - key: PYTHON_VERSION
    value: 3.13.5
  - key: ENABLE_DEBUG_LOGS
    value: False

  - key: GTAG_PROPERTY_ID
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: GOOGLE_ANALYTICS_PROPERTY_ID
    sync: false
  - key: SENTRY_DSN
    sync: false
